"""Bazel tools for interfacing with Carton"""

_HUB_BUILD_FILE = """\
\"\"\"Autogenerated by rules_perl.\"\"\"

load("@rules_perl//perl:perl_library.bzl", "perl_library")

DEPENDENCIES = {dependencies}
BINS = {bins}

perl_library(
    name = "{name}",
    deps = [
        "@{name}__" + dep
        for dep in DEPENDENCIES
    ],
    includes = [],
    visibility = ["//visibility:public"],
)

[
    alias(
        name = dep,
        actual = "@{name}__" + dep,
        visibility = ["//visibility:public"],
    )
    for dep in DEPENDENCIES
]

[
    alias(
        name = "{{}}_{{}}".format(dep, bin.replace("/", "_").replace(":", "")),
        actual = "@{name}__{{}}//:{{}}_{{}}".format(dep, dep, bin.replace("/", "_").replace(":", "")),
        visibility = ["//visibility:public"],
    )
    for dep, bins in BINS.items()
    for bin in bins
]

"""

def _cpan_hub_impl(repository_ctx):
    repository_ctx.file("WORKSPACE.bazel", """workspace(name = "{}")""".format(
        repository_ctx.name,
    ))

    repository_ctx.file("BUILD.bazel", _HUB_BUILD_FILE.format(
        name = repository_ctx.attr.hub_name,
        dependencies = json.encode_indent(repository_ctx.attr.modules, indent = " " * 4),
        bins = json.encode_indent(repository_ctx.attr.bins, indent = " " * 4),
    ))

cpan_hub = repository_rule(
    doc = "A hub repository that exposes all CPAN dependencies from a `cpanfile`.",
    implementation = _cpan_hub_impl,
    attrs = {
        "bins": attr.string_list_dict(
            doc = """
                Perl binary targets. Keys are packages, values are lists of bin paths.

                Example:

                    bins = {"App-cloc": ["bin/cloc"]},
                """,
            default = {},
        ),
        "hub_name": attr.string(
            doc = "The name of the hub.",
            mandatory = True,
        ),
        "modules": attr.string_list(
            doc = "Dependencies to add to the hub.",
            mandatory = True,
        ),
    },
)

_CPAN_MODULE_BUILD_FILE = """\
\"\"\"Autogenerated by rules_perl.\"\"\"

load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_perl//perl:perl_library.bzl", "perl_library")
load("@rules_perl//perl:perl_binary.bzl", "perl_binary")
load("@rules_perl//perl:defs.bzl", "perl_xs")

DEPENDENCIES = {dependencies}
XS_MODULES = {xs_modules}
BINS = {bins}

{cc_library}

{perl_xs}

perl_library(
    name = "{name}",
    srcs = glob(
        include = ["{output}**/*"],
        exclude = [
            "BUILD",
            "WORKSPACE",
            "*.bazel",
            "{output}t/**/*",
            "{output}xt/**/*",
        ],
    ) + XS_MODULES,
    includes = {includes},
    deps = [
        "@{hub_name}__" + dep
        for dep in DEPENDENCIES
    ],
    visibility = ["//visibility:public"],
)

[
    perl_binary(
        name = "{name}_{{}}".format(bin.replace("/", "_").replace(":", "")),
        main = bin,
        deps = [":{name}"],
        visibility = ["//visibility:public"],
    )
    for bin in BINS
]

alias(
    name = "{repo_name}",
    actual = "{name}",
    visibility = ["//visibility:public"],
)
"""

_PERL_XS = """
perl_xs(
    name = "{name}-xs",
    srcs = {srcs},
    defines = [
        "VERSION=\\"{version}\\"",
        "XS_VERSION=\\"{version}\\"",
    ],
    output_loc = "arch/auto/{module}",
    textual_hdrs = glob(
        include = ["**/*.h", "**/*.hpp"],
        allow_empty = True
    ) + {extra_headers},
    deps = {deps},
    {typemaps}
)
"""

_CC_LIBRARY = """
cc_library(
    name = "cc-lib",
    srcs = {srcs},
    hdrs = glob(
        include = ["**/*.h", "**/*.hpp"],
        allow_empty = True
    ) + {extra_headers},
    copts = ["-I."],
    includes = [
        "."
    ]
)
"""

def _get_files_from_repository(repository_ctx = None, parent = None):
    out = []
    pending = []

    if parent == None:
        parent = repository_ctx.path('.')

    if not parent.is_dir:
        fail("The target {} is not a directory".format(parent))

    pending = parent.readdir()
    parent = str(parent) + "/"

    for i in range(10000):
        if len(pending) == 0:
            return out
        child = pending.pop()
        if child.is_dir:
            pending.extend(child.readdir())
        else:
            out.append(str(child).replace(parent, ''))

    if len(pending) > 0:
        fail("The directory at {} has more than 10000 entries", parent)

def _get_xs_module_name(content):
    """Extracts the MODULE value from an XS file content string without regex."""
    for line in content.splitlines():
        # Strip leading/trailing whitespace
        line = line.strip()

        # The line MUST start with MODULE (either 'MODULE=' or 'MODULE ')
        if not line.startswith("MODULE"):
            continue

        line = line.replace("\t", " ")

        # 1. Normalize the line by splitting by whitespace to handle variable spaces
        # e.g., "MODULE  =  MyModule  PACKAGE = Main" -> ["MODULE", "=", "MyModule", "PACKAGE", "=", "Main"]
        # e.g., "MODULE=MyModule" -> ["MODULE=MyModule"]
        tokens = line.split(" ")

        # 2. Handle Case A: Compact syntax like "MODULE=MyModule"
        # (where 'MODULE=' is mashed into the first token)
        if tokens[0].startswith("MODULE="):
            # Split "MODULE=MyModule" by '=' and take the right side
            return tokens[0].split("=")[1].strip()

        # 3. Handle Case B: Spaced syntax like "MODULE = MyModule" or "MODULE MyModule"
        if len(tokens) > 1:
            if tokens[1] == "=":
                # If the second token is '=', the third token must be the value
                if len(tokens) > 2:
                    return tokens[2]
            else:
                # Legacy or loose XS syntax allows omitting '=': "MODULE MyModule"
                # Or handled cases where '=' was attached to the value: "MODULE =MyModule"
                if tokens[1].startswith("="):
                    return tokens[1].split("=")[1].strip()
                return tokens[1]

    return None  # Return None if no MODULE declaration was found

def _generate_perl_xs_entry(
        repository_ctx = None,
        module = None,
        xs_files = None,
        version = None,
        typemap = None,
        deps = [],
        extra_headers = [],
    ):

    if typemap:
        typemap = "typemaps = [\"{}\"],".format(typemap)

    xs = _PERL_XS.format(
        name = module,
        srcs = json.encode(xs_files),
        version = version,
        module = module.replace("-", "/") + "/" + module.rsplit("-", 2)[-1],
        typemaps = typemap if typemap else "",
        deps = json.encode(deps),
        extra_headers = json.encode_indent(extra_headers, indent = " " * 4)
    )

    return xs, "{}-xs".format(module)

def _cpan_distribution_archive_impl(repository_ctx):
    results = repository_ctx.download_and_extract(
        repository_ctx.attr.urls,
        sha256 = repository_ctx.attr.sha256,
        stripPrefix = repository_ctx.attr.strip_prefix,
    )

    output = ""
    includes = []
    lib_path = repository_ctx.path("lib")
    if lib_path.exists:
        includes = ["lib"]
    else:
        # In the event a lib directory doesn't exist, the module will need to be
        # extracted to a subdirectory.
        repository_ctx.delete(repository_ctx.path("."))
        output = ""
        split = repository_ctx.attr.distribution.split("-")
        if len(split) > 1:
            output = split[0]

        repository_ctx.download_and_extract(
            repository_ctx.attr.urls,
            sha256 = results.sha256,
            stripPrefix = repository_ctx.attr.strip_prefix,
            output = output,
        )

        includes = ["."]

    files = _get_files_from_repository(repository_ctx = repository_ctx)

    # Stringify extra headers so [Label(//:LMUconfig_h)] becomes ["@@//:LMUconfig_h"]
    # We don´t want to leak bzlmod internals into our rules, let Starlark deal with it
    extra_headers = [
        str(x) for x in repository_ctx.attr.extra_headers
    ]

    xs = ""
    xs_files = []
    cc_files = []
    cc_library = None
    typemap = None
    for x in files:
        if x.startswith('t/') or x.startswith('xt/'): # ignore tests
            continue
        if x.endswith('.xs'):
            xs_files.append(x)
        elif x.endswith('typemap'):
            typemap = x
        elif x.endswith('.c') or x.endswith('.cc') or x.endswith('.cpp'):
            cc_files.append(x)

    if cc_files:
        cc_library =_CC_LIBRARY.format(
            srcs = json.encode(cc_files),
            extra_headers = json.encode_indent(extra_headers, indent = " " * 4)
        )

    xs_targets = []
    if xs_files:
        includes.append("arch")
        module, dep = _generate_perl_xs_entry(
            repository_ctx = repository_ctx,
            module = repository_ctx.attr.distribution,
            xs_files = xs_files,
            version = repository_ctx.attr.version,
            typemap = typemap,
            deps = ["cc-lib"] if cc_files else [],
            extra_headers = extra_headers,
        )
        xs = xs + module
        xs_targets.append(dep)

    repository_ctx.file("WORKSPACE.bazel", """workspace(name = "{}")""".format(
        repository_ctx.name,
    ))

    repository_ctx.file("BUILD.bazel", _CPAN_MODULE_BUILD_FILE.format(
        name = repository_ctx.attr.distribution,
        hub_name = repository_ctx.attr.hub_name,
        repo_name = "{}__{}".format(repository_ctx.attr.hub_name, repository_ctx.attr.distribution),
        dependencies = json.encode_indent(repository_ctx.attr.dependencies, indent = " " * 4),
        output = "{}/".format(output).lstrip("/"),
        includes = json.encode(includes),
        bins = json.encode_indent(repository_ctx.attr.bins, indent = " " * 4),
        perl_xs = xs,
        cc_library = cc_library if cc_library else "",
        xs_modules = json.encode_indent(xs_targets, indent = " " * 4),
    ))

    return {
        "bins": repository_ctx.attr.bins,
        "dependencies": repository_ctx.attr.dependencies,
        "distribution": repository_ctx.attr.distribution,
        "hub_name": repository_ctx.attr.hub_name,
        "name": repository_ctx.name,
        "sha256": results.sha256,
        "strip_prefix": repository_ctx.attr.strip_prefix,
        "urls": repository_ctx.attr.urls,
        "version": repository_ctx.attr.version,
        "extra_headers": repository_ctx.attr.extra_headers,
    }

cpan_distribution_archive = repository_rule(
    doc = "A repository rule for fetching Perl modules from CPAN and instantiating a target for it.",
    implementation = _cpan_distribution_archive_impl,
    attrs = {
        "bins": attr.string_list(
            doc = "List of paths to create perl_binary targets for.",
            default = [],
        ),
        "extra_headers": attr.label_list(
            doc = "Extra headers to inject into the generated perl_xs module.",
            default = [],
        ),
        "dependencies": attr.string_list(
            doc = "The dependencies of the current module.",
            mandatory = True,
        ),
        "distribution": attr.string(
            doc = "The distribution of the module as described in the CPAN Metadata, e.g. `Capture-Tiny-0.48`",
            mandatory = True,
        ),
        "hub_name": attr.string(
            doc = "The name of the bzlmod hub repository.",
            mandatory = True,
        ),
        "sha256": attr.string(
            doc = "The expected SHA-256 of the file downloaded.",
        ),
        "strip_prefix": attr.string(
            doc = "A directory prefix to strip from the extracted files.",
        ),
        "urls": attr.string_list(
            doc = "List of mirror URLs referencing the same file to download.",
            mandatory = True,
        ),
        "version": attr.string(
            doc = "Version of the module, used for XS support",
        )
    },
)

def install(*, module_ctx, attrs):
    """Instantiate the cpan module for the given `install` tag_class attributes.

    Args:
        module_ctx (module_ctx): The current module context.
        attrs (struct): The attributes from the `install` tag class.

    Returns:
        str: The name of the hub repository for the current tag_class.
    """
    lock_file = module_ctx.path(attrs.lock)
    module_ctx.watch(lock_file)
    lockfile = json.decode(module_ctx.read(lock_file))

    for module in lockfile:
        repo_name = "{}__{}".format(attrs.name, module)
        cpan_distribution_archive(
            name = repo_name,
            urls = [lockfile[module]["url"]],
            strip_prefix = lockfile[module]["strip_prefix"],
            sha256 = lockfile[module]["sha256"],
            hub_name = attrs.name,
            distribution = module,
            dependencies = lockfile[module]["dependencies"] + attrs.add_deps.get(module, []),
            bins = attrs.bins.get(module, []),
            version = str(lockfile[module].get("version", "invalid")),
            extra_headers = attrs.extra_headers.get(module, []),
        )

    cpan_hub(
        name = attrs.name,
        hub_name = attrs.name,
        modules = lockfile.keys(),
        bins = attrs.bins,
    )

    return attrs.name
